// This file is autogenerated by scripts/build-internal-registry.ts
// Do not edit this file directly.
import * as React from "react";

import type { DemoName } from "@/registry/demos";

export const Index: Record<
  DemoName,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
  "badge-default": {
    files: ["registry/src/badge-default/badge-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/badge-default")),
  },
  "badge-sizes": {
    files: ["registry/src/badge-sizes/badge-sizes.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/badge-sizes")),
  },
  "badge-variants": {
    files: ["registry/src/badge-variants/badge-variants.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/badge-variants")),
  },
  "button-default": {
    files: ["registry/src/button-default/button-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-default")),
  },
  "button-disabled": {
    files: ["registry/src/button-disabled/button-disabled.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-disabled")),
  },
  "button-hint": {
    files: ["registry/src/button-hint/button-hint.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-hint")),
  },
  "button-icon-button": {
    files: ["registry/src/button-icon-button/button-icon-button.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/button-icon-button"),
    ),
  },
  "button-nav-icon": {
    files: ["registry/src/button-nav-icon/button-nav-icon.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-nav-icon")),
  },
  "button-sizes": {
    files: ["registry/src/button-sizes/button-sizes.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-sizes")),
  },
  "button-variants": {
    files: ["registry/src/button-variants/button-variants.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-variants")),
  },
  "button-warning": {
    files: ["registry/src/button-warning/button-warning.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/button-warning")),
  },
  "checkbox-default": {
    files: ["registry/src/checkbox-default/checkbox-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/checkbox-default"),
    ),
  },
  "checkbox-sizes": {
    files: ["registry/src/checkbox-sizes/checkbox-sizes.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/checkbox-sizes")),
  },
  "code-block-controlled": {
    files: ["registry/src/code-block-controlled/code-block-controlled.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/code-block-controlled"),
    ),
  },
  "code-block-default": {
    files: ["registry/src/code-block-default/code-block-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/code-block-default"),
    ),
  },
  "code-block-mermaid": {
    files: ["registry/src/code-block-mermaid/code-block-mermaid.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/code-block-mermaid"),
    ),
  },
  "code-block-readonly": {
    files: ["registry/src/code-block-readonly/code-block-readonly.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/code-block-readonly"),
    ),
  },
  "cover-default": {
    files: ["registry/src/cover-default/cover-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/cover-default")),
  },
  "cover-picker": {
    files: ["registry/src/cover-picker/cover-picker.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/cover-picker")),
  },
  "icon-block-emoji": {
    files: ["registry/src/icon-block-emoji/icon-block-emoji.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-block-emoji"),
    ),
  },
  "icon-block-lucide": {
    files: ["registry/src/icon-block-lucide/icon-block-lucide.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-block-lucide"),
    ),
  },
  "icon-block-sizes": {
    files: ["registry/src/icon-block-sizes/icon-block-sizes.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-block-sizes"),
    ),
  },
  "icon-block-text": {
    files: ["registry/src/icon-block-text/icon-block-text.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/icon-block-text")),
  },
  "icon-block-url": {
    files: ["registry/src/icon-block-url/icon-block-url.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/icon-block-url")),
  },
  "icon-menu-custom-factory": {
    files: [
      "registry/src/icon-menu-custom-factory/icon-menu-custom-factory.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-menu-custom-factory"),
    ),
  },
  "icon-menu-default": {
    files: ["registry/src/icon-menu-default/icon-menu-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-menu-default"),
    ),
  },
  "icon-menu-notion-icons": {
    files: ["registry/src/icon-menu-notion-icons/icon-menu-notion-icons.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/icon-menu-notion-icons"),
    ),
  },
  "input-default": {
    files: ["registry/src/input-default/input-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/input-default")),
  },
  "input-flat": {
    files: ["registry/src/input-flat/input-flat.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/input-flat")),
  },
  "input-search": {
    files: ["registry/src/input-search/input-search.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/input-search")),
  },
  "login-form-auth": {
    files: ["registry/src/login-form-auth/login-form-auth.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/login-form-auth")),
  },
  "login-form-default": {
    files: ["registry/src/login-form-default/login-form-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/login-form-default"),
    ),
  },
  "multi-select-creatable": {
    files: ["registry/src/multi-select-creatable/multi-select-creatable.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/multi-select-creatable"),
    ),
  },
  "multi-select-default": {
    files: ["registry/src/multi-select-default/multi-select-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/multi-select-default"),
    ),
  },
  "multi-select-inline": {
    files: ["registry/src/multi-select-inline/multi-select-inline.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/multi-select-inline"),
    ),
  },
  "multi-select-max-selected": {
    files: [
      "registry/src/multi-select-max-selected/multi-select-max-selected.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/multi-select-max-selected"),
    ),
  },
  "navbar-menu": {
    files: ["registry/src/navbar-menu/navbar-menu.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/navbar-menu")),
  },
  "navbar-notion": {
    files: [
      "registry/src/navbar-notion/data.ts",
      "registry/src/navbar-notion/navbar-notion.tsx",
    ],
    component: React.lazy(() => import("@notion-kit/registry/navbar-notion")),
  },
  "navbar-participants": {
    files: ["registry/src/navbar-participants/navbar-participants.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/navbar-participants"),
    ),
  },
  "navbar-sharing": {
    files: ["registry/src/navbar-sharing/navbar-sharing.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/navbar-sharing")),
  },
  "navbar-title": {
    files: ["registry/src/navbar-title/navbar-title.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/navbar-title")),
  },
  "resizable-demo": {
    files: ["registry/src/resizable-demo/resizable-demo.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/resizable-demo")),
  },
  "select-custom": {
    files: ["registry/src/select-custom/select-custom.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/select-custom")),
  },
  "select-default": {
    files: ["registry/src/select-default/select-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/select-default")),
  },
  "separator-demo": {
    files: ["registry/src/separator-demo/separator-demo.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/separator-demo")),
  },
  "settings-panel-connections-table": {
    files: [
      "registry/src/settings-panel-connections-table/settings-panel-connections-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-connections-table"),
    ),
  },
  "settings-panel-guests-table": {
    files: [
      "registry/src/settings-panel-guests-table/settings-panel-guests-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-guests-table"),
    ),
  },
  "settings-panel-invitations-table": {
    files: [
      "registry/src/settings-panel-invitations-table/settings-panel-invitations-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-invitations-table"),
    ),
  },
  "settings-panel-members-table": {
    files: [
      "registry/src/settings-panel-members-table/settings-panel-members-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-members-table"),
    ),
  },
  "settings-panel-notion": {
    files: [
      "registry/src/settings-panel-notion/data.ts",
      "registry/src/settings-panel-notion/settings-panel-notion.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-notion"),
    ),
  },
  "settings-panel-plans-table": {
    files: [
      "registry/src/settings-panel-plans-table/settings-panel-plans-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-plans-table"),
    ),
  },
  "settings-panel-sessions-table": {
    files: [
      "registry/src/settings-panel-sessions-table/settings-panel-sessions-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-sessions-table"),
    ),
  },
  "settings-panel-teamspaces-table": {
    files: [
      "registry/src/settings-panel-teamspaces-table/settings-panel-teamspaces-table.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/settings-panel-teamspaces-table"),
    ),
  },
  "sidebar-basic": {
    files: ["registry/src/sidebar-basic/sidebar-basic.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/sidebar-basic")),
  },
  "sidebar-favorite-list": {
    files: ["registry/src/sidebar-favorite-list/sidebar-favorite-list.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/sidebar-favorite-list"),
    ),
  },
  "sidebar-notion": {
    files: [
      "registry/src/sidebar-notion/data.ts",
      "registry/src/sidebar-notion/sidebar-notion.tsx",
    ],
    component: React.lazy(() => import("@notion-kit/registry/sidebar-notion")),
  },
  "sidebar-page-list": {
    files: ["registry/src/sidebar-page-list/sidebar-page-list.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/sidebar-page-list"),
    ),
  },
  "sidebar-search-command": {
    files: ["registry/src/sidebar-search-command/sidebar-search-command.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/sidebar-search-command"),
    ),
  },
  "sidebar-trash-box": {
    files: ["registry/src/sidebar-trash-box/sidebar-trash-box.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/sidebar-trash-box"),
    ),
  },
  "sidebar-workspace-switcher": {
    files: [
      "registry/src/sidebar-workspace-switcher/sidebar-workspace-switcher.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/sidebar-workspace-switcher"),
    ),
  },
  "single-image-dropzone-default": {
    files: [
      "registry/src/single-image-dropzone-default/single-image-dropzone-default.tsx",
    ],
    component: React.lazy(
      () => import("@notion-kit/registry/single-image-dropzone-default"),
    ),
  },
  "skeleton-demo": {
    files: ["registry/src/skeleton-demo/skeleton-demo.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/skeleton-demo")),
  },
  "spinner-default": {
    files: ["registry/src/spinner-default/spinner-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/spinner-default")),
  },
  "spinner-variants": {
    files: ["registry/src/spinner-variants/spinner-variants.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/spinner-variants"),
    ),
  },
  "switch-default": {
    files: ["registry/src/switch-default/switch-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/switch-default")),
  },
  "switch-sizes": {
    files: ["registry/src/switch-sizes/switch-sizes.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/switch-sizes")),
  },
  "table-view-controlled": {
    files: ["registry/src/table-view-controlled/table-view-controlled.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/table-view-controlled"),
    ),
  },
  "table-view-uncontrolled": {
    files: ["registry/src/table-view-uncontrolled/table-view-uncontrolled.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/table-view-uncontrolled"),
    ),
  },
  "tabs-demo": {
    files: ["registry/src/tabs-demo/tabs-demo.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/tabs-demo")),
  },
  "tags-input-default": {
    files: ["registry/src/tags-input-default/tags-input-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/tags-input-default"),
    ),
  },
  "tooltip-demo": {
    files: ["registry/src/tooltip-demo/tooltip-demo.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/tooltip-demo")),
  },
  "tree-command": {
    files: ["registry/src/tree-command/tree-command.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/tree-command")),
  },
  "tree-default": {
    files: ["registry/src/tree-default/tree-default.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/tree-default")),
  },
  "tree-multi-select": {
    files: ["registry/src/tree-multi-select/tree-multi-select.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/tree-multi-select"),
    ),
  },
  "tree-non-collapsible": {
    files: ["registry/src/tree-non-collapsible/tree-non-collapsible.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/tree-non-collapsible"),
    ),
  },
  "tree-show-empty": {
    files: ["registry/src/tree-show-empty/tree-show-empty.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/tree-show-empty")),
  },
  "unsplash-default": {
    files: ["registry/src/unsplash-default/unsplash-default.tsx"],
    component: React.lazy(
      () => import("@notion-kit/registry/unsplash-default"),
    ),
  },
  "unsplash-search": {
    files: ["registry/src/unsplash-search/unsplash-search.tsx"],
    component: React.lazy(() => import("@notion-kit/registry/unsplash-search")),
  },
};
