// This file is autogenerated by scripts/build-internal-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index: Record<
  string,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
  "button/default": {
    files: ["components/demos/button/default.tsx"],
    component: React.lazy(() => import("@/components/demos/button/default")),
  },
  "button/disabled": {
    files: ["components/demos/button/disabled.tsx"],
    component: React.lazy(() => import("@/components/demos/button/disabled")),
  },
  "button/hint": {
    files: ["components/demos/button/hint.tsx"],
    component: React.lazy(() => import("@/components/demos/button/hint")),
  },
  "button/icon-button": {
    files: ["components/demos/button/icon-button.tsx"],
    component: React.lazy(
      () => import("@/components/demos/button/icon-button"),
    ),
  },
  "button/nav-icon": {
    files: ["components/demos/button/nav-icon.tsx"],
    component: React.lazy(() => import("@/components/demos/button/nav-icon")),
  },
  "button/sizes": {
    files: ["components/demos/button/sizes.tsx"],
    component: React.lazy(() => import("@/components/demos/button/sizes")),
  },
  "button/variants": {
    files: ["components/demos/button/variants.tsx"],
    component: React.lazy(() => import("@/components/demos/button/variants")),
  },
  "button/warning": {
    files: ["components/demos/button/warning.tsx"],
    component: React.lazy(() => import("@/components/demos/button/warning")),
  },
  "input/default": {
    files: ["components/demos/input/default.tsx"],
    component: React.lazy(() => import("@/components/demos/input/default")),
  },
  "input/flat": {
    files: ["components/demos/input/flat.tsx"],
    component: React.lazy(() => import("@/components/demos/input/flat")),
  },
  "input/search": {
    files: ["components/demos/input/search.tsx"],
    component: React.lazy(() => import("@/components/demos/input/search")),
  },
};
