packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.23.0
  prettier: ^3.4.2
  tsup: ^8.4.0
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  node22:
    "@types/node": ^22.10.0
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
  next14:
    next: ^14.2.15
  next15:
    next: ^15.2.0
  vitest:
    "vitest": ^2.1.8
    "@vitejs/plugin-react": ^4.3.4
    "@vitest/coverage-v8": ^2.1.8
    "@vitest/ui": ^2.1.8
  rtl:
    jsdom: ^25.0.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/react": ^16.1.0
    "@testing-library/user-event": ^14.5.2
  turbo:
    turbo: ^2.3.4
    "@turbo/gen": ^2.3.4
  tailwind-v4:
    tailwindcss: ^4.1.0
    "@tailwindcss/postcss": ^4.1.0
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.456.0
    next-themes: ^0.4.4
    react-hook-form: ^7.54.2
    react-hotkeys-hook: 4.6.1
    sonner: ^1.7.2
    usehooks-ts: ^3.1.1
    "@dnd-kit/core": ^6.3.1
    "@dnd-kit/modifiers": ^9.0.0
    "@dnd-kit/sortable": ^10.0.0
    "@hookform/resolvers": ^3.10.0
    "@tanstack/react-table": ^8.20.6
  uuid:
    uuid: ^11.1.0
