packages:
  - apps/*
  - examples/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.39.1
  prettier: ^3.6.2
  tsdown: ^0.16.6
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  node22:
    "@types/node": ^22.10.0
  react19:
    react: ^19.2.3
    react-dom: ^19.2.3
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
  next16:
    next: ^16.1.0
    "@next/eslint-plugin-next": ^16.1.0
  test:
    msw: ^2.12.4
    msw-storybook-addon: ^2.0.6
    playwright: ^1.57.0
    vitest: ^4.0.16
    "@vitejs/plugin-react": ^4.3.4
    "@vitest/browser-playwright": ^4.0.16
    "@vitest/coverage-v8": ^4.0.16
    "@vitest/ui": ^2.1.8
  rtl:
    jsdom: ^25.0.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/react": ^16.1.0
    "@testing-library/user-event": ^14.5.2
  turbo:
    turbo: ^2.6.0
    "@turbo/gen": ^2.6.0
    eslint-plugin-turbo: ^2.6.0
  tailwind-v4:
    tailwindcss: ^4.1.16
    "@tailwindcss/postcss": ^4.1.16
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.456.0
    react-hook-form: ^7.66.0
    react-hotkeys-hook: ^5.2.1
    usehooks-ts: ^3.1.1
    "@dnd-kit/core": ^6.3.1
    "@dnd-kit/modifiers": ^9.0.0
    "@dnd-kit/sortable": ^10.0.0
    "@hookform/resolvers": ^5.2.2
    "@tanstack/react-query": ^5.81.5
    "@tanstack/react-table": ^8.21.3
  uuid:
    uuid: ^13.0.0
  env:
    dotenv-cli: ^8.0.0
    "@t3-oss/env-nextjs": ^0.13.6
