packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.26.0
  prettier: ^3.4.2
  tsup: ^8.4.0
  typescript: ^5.7.3
  zod: ^3.24.1

catalogs:
  node22:
    "@types/node": ^22.10.0
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.3
    "@types/react-dom": ^19.1.3
  next14:
    next: ^14.2.15
  next15:
    next: ^15.3.2
    "@next/eslint-plugin-next": ^15.3.2
  vitest:
    "vitest": ^2.1.8
    "@vitejs/plugin-react": ^4.3.4
    "@vitest/coverage-v8": ^2.1.8
    "@vitest/ui": ^2.1.8
  rtl:
    jsdom: ^25.0.1
    "@testing-library/jest-dom": ^6.6.3
    "@testing-library/react": ^16.1.0
    "@testing-library/user-event": ^14.5.2
  turbo:
    turbo: ^2.5.3
    "@turbo/gen": ^2.5.3
    eslint-plugin-turbo: ^2.5.3
  tailwind-v4:
    tailwindcss: ^4.1.0
    "@tailwindcss/postcss": ^4.1.0
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.456.0
    react-hook-form: ^7.56.3
    react-hotkeys-hook: 4.6.1
    usehooks-ts: ^3.1.1
    zustand: ^5.0.3
    "@dnd-kit/core": ^6.3.1
    "@dnd-kit/modifiers": ^9.0.0
    "@dnd-kit/sortable": ^10.0.0
    "@hookform/resolvers": ^5.0.1
    "@tanstack/react-table": ^8.21.3
  uuid:
    uuid: ^11.1.0
  env:
    dotenv-cli: ^8.0.0
    "@t3-oss/env-nextjs": ^0.13.6
