import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";

import { DemoName, DEMOS } from "@/registry/demos";

const INTERNAL_REGISTRY_PATH = path.join(process.cwd(), "src/__registry__");
const REGISTRY_SRC_PATH = path.join(
  process.cwd(),
  "../../packages/registry/src",
);

async function setup() {
  const targetPath = INTERNAL_REGISTRY_PATH;
  rimraf.sync(targetPath);
  if (!existsSync(targetPath)) {
    await fs.mkdir(targetPath, { recursive: true });
  }
  const autogeneratedFilePath = path.join(targetPath, ".autogenerated");
  await fs.writeFile(
    autogeneratedFilePath,
    "This directory is autogenerated. Do not edit its contents directly.",
    "utf8",
  );
}

async function discoverFiles(demoName: DemoName): Promise<string[]> {
  const demoDir = path.join(REGISTRY_SRC_PATH, demoName);
  const entries = await fs.readdir(demoDir);
  return entries
    .filter((file) => file !== "index.ts")
    .map((file) => `registry/src/${demoName}/${file}`);
}

async function buildDemos() {
  const targetPath = INTERNAL_REGISTRY_PATH;

  let index = `// This file is autogenerated by scripts/build-internal-registry.ts
// Do not edit this file directly.
import * as React from "react";

import type { DemoName } from "@/registry/demos";

export const Index: Record<
  DemoName,
  {
    files: string[];
    component: React.LazyExoticComponent<React.ComponentType<object>>;
  }
> = {
`;

  for (const name of DEMOS) {
    const files = await discoverFiles(name);
    const filesStr = files.map((file) => `"${file}"`).join(", ");
    const importPath = `@notion-kit/registry/${name}`;

    index += `  "${name}": {
    files: [${filesStr}],
    component: React.lazy(() => import("${importPath}")),
  },
`;
  }

  index += `};
`;
  rimraf.sync(path.join(targetPath, "demos.tsx"));
  await fs.writeFile(path.join(targetPath, "demos.tsx"), index, "utf8");
}

async function run() {
  try {
    await setup();
    await buildDemos();
    console.log("✅ Done!");
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

void run();
