export const CODE_BLOCK_LANGUAGES = [
  { value: "abap", label: "ABAP" },
  { value: "agda", label: "Agda" },
  { value: "arduino", label: "Arduino" },
  { value: "ascii-art", label: "ASCII Art" },
  { value: "assembly", label: "Assembly" },
  { value: "bash", label: "Bash" },
  { value: "basic", label: "BASIC" },
  { value: "bnf", label: "BNF" },
  { value: "c", label: "C" },
  { value: "csharp", label: "C#" },
  { value: "cpp", label: "C++" },
  { value: "clojure", label: "Clojure" },
  { value: "coffeescript", label: "CoffeeScript" },
  { value: "css", label: "CSS" },
  { value: "dart", label: "Dart" },
  { value: "dhall", label: "Dhall" },
  { value: "diff", label: "Diff" },
  { value: "docker", label: "Docker" },
  { value: "ebnf", label: "EBNF" },
  { value: "elixir", label: "Elixir" },
  { value: "elm", label: "Elm" },
  { value: "erlang", label: "Erlang" },
  { value: "fsharp", label: "F#" },
  { value: "flow", label: "Flow" },
  { value: "fortran", label: "Fortran" },
  { value: "gherkin", label: "Gherkin" },
  { value: "glsl", label: "GLSL" },
  { value: "go", label: "Go" },
  { value: "graphql", label: "GraphQL" },
  { value: "groovy", label: "Groovy" },
  { value: "haskell", label: "Haskell" },
  { value: "hcl", label: "HCL" },
  { value: "html", label: "HTML" },
  { value: "idris", label: "Idris" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "json", label: "JSON" },
  { value: "julia", label: "Julia" },
  { value: "kotlin", label: "Kotlin" },
  { value: "latex", label: "LaTeX" },
  { value: "less", label: "Less" },
  { value: "lisp", label: "Lisp" },
  { value: "livescript", label: "LiveScript" },
  { value: "llvm", label: "LLVM IR" },
  { value: "lua", label: "Lua" },
  { value: "makefile", label: "Makefile" },
  { value: "markdown", label: "Markdown" },
  { value: "markup", label: "Markup" },
  { value: "mathematica", label: "Mathematica" },
  { value: "matlab", label: "MATLAB" },
  { value: "mermaid", label: "Mermaid" },
  { value: "nix", label: "Nix" },
  { value: "notion-formula", label: "Notion Formula" },
  { value: "objective-c", label: "Objective-C" },
  { value: "ocaml", label: "OCaml" },
  { value: "pascal", label: "Pascal" },
  { value: "perl", label: "Perl" },
  { value: "php", label: "PHP" },
  { value: "text", label: "Plain Text" },
  { value: "powershell", label: "PowerShell" },
  { value: "prolog", label: "Prolog" },
  { value: "protobuf", label: "Protobuf" },
  { value: "purescript", label: "PureScript" },
  { value: "python", label: "Python" },
  { value: "r", label: "R" },
  { value: "racket", label: "Racket" },
  { value: "reason", label: "Reason" },
  { value: "rocq", label: "Rocq" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "sass", label: "Sass" },
  { value: "scala", label: "Scala" },
  { value: "scheme", label: "Scheme" },
  { value: "scss", label: "SCSS" },
  { value: "shell", label: "Shell" },
  { value: "smalltalk", label: "Smalltalk" },
  { value: "solidity", label: "Solidity" },
  { value: "sql", label: "SQL" },
  { value: "swift", label: "Swift" },
  { value: "toml", label: "TOML" },
  { value: "typescript", label: "TypeScript" },
  { value: "vbnet", label: "VB.Net" },
  { value: "verilog", label: "Verilog" },
  { value: "vhdl", label: "VHDL" },
  { value: "visual-basic", label: "Visual Basic" },
  { value: "webassembly", label: "WebAssembly" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
];

export const CODE_BLOCK_THEMES = [
  { value: "andromeeda", label: "Andromeeda" },
  { value: "aurora-x", label: "Aurora X" },
  { value: "ayu-dark", label: "Ayu Dark" },
  { value: "ayu-light", label: "Ayu Light" },
  { value: "ayu-mirage", label: "Ayu Mirage" },
  { value: "catppuccin-frappe", label: "Catppuccin Frappé" },
  { value: "catppuccin-latte", label: "Catppuccin Latte" },
  { value: "catppuccin-macchiato", label: "Catppuccin Macchiato" },
  { value: "catppuccin-mocha", label: "Catppuccin Mocha" },
  { value: "dark-plus", label: "Dark Plus" },
  { value: "dracula", label: "Dracula Theme" },
  { value: "dracula-soft", label: "Dracula Theme Soft" },
  { value: "everforest-dark", label: "Everforest Dark" },
  { value: "everforest-light", label: "Everforest Light" },
  { value: "github-dark", label: "GitHub Dark" },
  { value: "github-dark-default", label: "GitHub Dark Default" },
  { value: "github-dark-dimmed", label: "GitHub Dark Dimmed" },
  { value: "github-dark-high-contrast", label: "GitHub Dark High Contrast" },
  { value: "github-light", label: "GitHub Light" },
  { value: "github-light-default", label: "GitHub Light Default" },
  { value: "github-light-high-contrast", label: "GitHub Light High Contrast" },
  { value: "gruvbox-dark-hard", label: "Gruvbox Dark Hard" },
  { value: "gruvbox-dark-medium", label: "Gruvbox Dark Medium" },
  { value: "gruvbox-dark-soft", label: "Gruvbox Dark Soft" },
  { value: "gruvbox-light-hard", label: "Gruvbox Light Hard" },
  { value: "gruvbox-light-medium", label: "Gruvbox Light Medium" },
  { value: "gruvbox-light-soft", label: "Gruvbox Light Soft" },
  { value: "horizon", label: "Horizon" },
  { value: "houston", label: "Houston" },
  { value: "kanagawa-dragon", label: "Kanagawa Dragon" },
  { value: "kanagawa-lotus", label: "Kanagawa Lotus" },
  { value: "kanagawa-wave", label: "Kanagawa Wave" },
  { value: "laserwave", label: "LaserWave" },
  { value: "light-plus", label: "Light Plus" },
  { value: "material-theme", label: "Material Theme" },
  { value: "material-theme-darker", label: "Material Theme Darker" },
  { value: "material-theme-lighter", label: "Material Theme Lighter" },
  { value: "material-theme-ocean", label: "Material Theme Ocean" },
  { value: "material-theme-palenight", label: "Material Theme Palenight" },
  { value: "min-dark", label: "Min Dark" },
  { value: "min-light", label: "Min Light" },
  { value: "monokai", label: "Monokai" },
  { value: "night-owl", label: "Night Owl" },
  { value: "night-owl-light", label: "Night Owl Light" },
  { value: "nord", label: "Nord" },
  { value: "one-dark-pro", label: "One Dark Pro" },
  { value: "one-light", label: "One Light" },
  { value: "plastic", label: "Plastic" },
  { value: "poimandres", label: "Poimandres" },
  { value: "red", label: "Red" },
  { value: "rose-pine", label: "Rosé Pine" },
  { value: "rose-pine-dawn", label: "Rosé Pine Dawn" },
  { value: "rose-pine-moon", label: "Rosé Pine Moon" },
  { value: "slack-dark", label: "Slack Dark" },
  { value: "slack-ochin", label: "Slack Ochin" },
  { value: "snazzy-light", label: "Snazzy Light" },
  { value: "solarized-dark", label: "Solarized Dark" },
  { value: "solarized-light", label: "Solarized Light" },
  { value: "synthwave-84", label: "Synthwave '84" },
  { value: "tokyo-night", label: "Tokyo Night" },
  { value: "vesper", label: "Vesper" },
  { value: "vitesse-black", label: "Vitesse Black" },
  { value: "vitesse-dark", label: "Vitesse Dark" },
  { value: "vitesse-light", label: "Vitesse Light" },
];
