import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: ["src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary) / <alpha-value>)",
        secondary: "rgba(var(--secondary))",
        muted: "rgba(var(--muted))",
        icon: "rgba(var(--icon))",
        main: "rgb(var(--bg-main) / <alpha-value>)",
        input: "rgb(var(--bg-input) / <alpha-value>)",
        sidebar: {
          DEFAULT: "rgb(var(--bg-sidebar) / <alpha-value>)",
          primary: "rgb(var(--sidebar-primary) / <alpha-value>)",
        },
        modal: "rgb(var(--bg-modal) / <alpha-value>)",
        popover: "rgb(var(--bg-popover) / <alpha-value>)",
        tooltip: {
          DEFAULT: "rgb(var(--bg-tooltip) / <alpha-value>)",
          primary: "rgba(var(--tooltip-primary))",
          secondary: "rgba(var(--tooltip-secondary))",
        },
        border: {
          DEFAULT: "rgba(var(--primary) / 0.10)",
          button: "rgba(var(--primary) / 0.15)",
          cell: "rgb(var(--border-cell) / <alpha-value>)",
        },
        ring: "rgba(var(--ring))",
        blue: {
          DEFAULT: "rgb(35, 131, 226)",
          hover: "rgb(0, 119, 212)",
        },
        red: "rgb(235, 87, 87)",
        orange: "rgb(218, 163, 64)",
        /** Generated by Shadcn */
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
    },
  },
} satisfies Config;
